#ifndef _TESTHELPERS_H_
#define _TESTHELPERS_H_

#define CPPUNIT_ASSERT_NOT_NULL(actual) CPPUNIT_ASSERT(actual != NULL)
#define CPPUNIT_ASSERT_NULL(actual) CPPUNIT_ASSERT(actual == NULL)

#endif // _TESTHELPERS_H_